### ISSUE TITLE
install fails with error with in meson depfixer.py

### ISSUE THREAD

**Issue by travisdowns** [obilaniu/libpfc#6]
I'm not any kind of meson expert so I haven't been able to solve this one, but currently the `ninja install` step is failing with an error `AttributeError: 'NoneType' object has no attribute 'sh_offset'`. 

The full error output is below:

```
[1/2] 'Generating kmod with a custom command.'
make -C /lib/modules/4.4.0-81-generic/build M=/home/tdowns/dev/uarch-bench/libpfc/build/kmod/kmod.dir modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-81-generic'
  CC [M]  /home/tdowns/dev/uarch-bench/libpfc/build/kmod/kmod.dir/pfckmod.o
  LD [M]  /home/tdowns/dev/uarch-bench/libpfc/build/kmod/kmod.dir/pfc.o
  Building modules, stage 2.
  MODPOST 1 modules
  LD [M]  /home/tdowns/dev/uarch-bench/libpfc/build/kmod/kmod.dir/pfc.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-81-generic'
[1/2] Installing files.
Installing kmod/pfc.ko to /home/tdowns/dev/uarch-bench/libpfc-bin/bin/pfc.ko
Traceback (most recent call last):
  File "/home/tdowns/bin/meson-0.34.0/meson.py", line 24, in <module>
    sys.exit(mesonmain.run(thisfile, sys.argv[1:]))
  File "/home/tdowns/bin/meson-0.34.0/mesonbuild/mesonmain.py", line 242, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/tdowns/bin/meson-0.34.0/mesonbuild/mesonmain.py", line 232, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/tdowns/bin/meson-0.34.0/mesonbuild/scripts/meson_install.py", line 251, in run
    do_install(datafilename)
  File "/home/tdowns/bin/meson-0.34.0/mesonbuild/scripts/meson_install.py", line 54, in do_install
    install_targets(d)
  File "/home/tdowns/bin/meson-0.34.0/mesonbuild/scripts/meson_install.py", line 231, in install_targets
    e = depfixer.Elf(outname, False)
  File "/home/tdowns/bin/meson-0.34.0/mesonbuild/scripts/depfixer.py", line 123, in __init__
    self.parse_dynamic()
  File "/home/tdowns/bin/meson-0.34.0/mesonbuild/scripts/depfixer.py", line 200, in parse_dynamic
    self.bf.seek(sec.sh_offset)
AttributeError: 'NoneType' object has no attribute 'sh_offset'
FAILED: install 
'/usr/bin/python3' '/home/tdowns/bin/meson-0.34.0/meson.py' '--internal' 'install' '/home/tdowns/dev/uarch-bench/libpfc/build/meson-private/install.dat'
ninja: build stopped: subcommand failed.
```
I'm not sure what this sh_offset stuff is trying to do: some type of modification of the binary at install time? ... and it fails because it can't find the right section?

**Comment by obilaniu** [comment]
@travisdowns I think frankly that I should update my `meson.build` definitions so that the project builds with the modern Meson version, `0.41.0`. `0.34` is very old. Will do so promptly (next few minutes).

**Comment by travisdowns** [comment]
It seems like the issue is that `pfc.ko` doesn't have a `.dynamic` section, which the meson build doesn't handle. `depfixer.py` requires that section so bails when it isn't present:

```
        def parse_dynamic(self):
        sec = self.find_section(b'.dynamic')
        self.dynamic = []
        self.bf.seek(sec.sh_offset)
        while True:
            e = DynamicEntry(self.bf, self.ptrsize, self.is_le)
            self.dynamic.append(e)
            if e.d_tag == 0:
                break
```

`readelf --sections kmod/pfc.ko | grep dynamic` returns nothing on my system (but `libpfc.so` does have one, for example).

**Comment by obilaniu** [comment]
@travisdowns Could you please check whether the build works with Meson `0.41.0`? I just tried and it works flawlessly...

**Comment by travisdowns** [comment]
Yes. Can you try the `readelf` command I used above to see if _your_ binary has a `.dynamic` section for some reason?

**Comment by travisdowns** [comment]
Still haven't tried it, but seems like it's fixed in 0.41.0:

https://github.com/mesonbuild/meson/blob/master/mesonbuild/scripts/depfixer.py#L199

**Comment by obilaniu** [comment]
@travisdowns `readelf --sections kmod/pfc.ko | grep dynamic` reports no `.dynamic` section here.

**Comment by obilaniu** [comment]
@travisdowns I pushed a small change updating the required Meson version to 0.41.0.

**Comment by travisdowns** [comment]
Success with `0.41.0` !

```
tdowns@host:~/dev/uarch-bench/libpfc/build$ ninja install
[1/2] Generating kmod with a custom command.
make -C /lib/modules/4.4.0-81-generic/build M=/home/tdowns/dev/uarch-bench/libpfc/build/kmod/kmod.dir modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-81-generic'
  CC [M]  /home/tdowns/dev/uarch-bench/libpfc/build/kmod/kmod.dir/pfckmod.o
  LD [M]  /home/tdowns/dev/uarch-bench/libpfc/build/kmod/kmod.dir/pfc.o
  Building modules, stage 2.
  MODPOST 1 modules
  LD [M]  /home/tdowns/dev/uarch-bench/libpfc/build/kmod/kmod.dir/pfc.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-81-generic'
[1/2] Installing files.
Installing src/libpfc.so to /home/tdowns/dev/uarch-bench/libpfc-bin/lib/x86_64-linux-gnu/libpfc.so
Installing src/pfcdemo to /home/tdowns/dev/uarch-bench/libpfc-bin/bin/pfcdemo
Installing kmod/pfc.ko to /home/tdowns/dev/uarch-bench/libpfc-bin/bin/pfc.ko
Installing libpfc.h to /home/tdowns/dev/uarch-bench/libpfc-bin/include/
tdowns@host:~/dev/uarch-bench/libpfc/build$ meson --version
0.41.0
tdowns@host:~/dev/uarch-bench/libpfc/build$
